apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pdb.yaml

labels:
  - pairs:
      app.kubernetes.io/name: bible-reader
      app.kubernetes.io/part-of: bible-reader
    includeSelectors: true

images:
  - name: bible-reader
    newTag: 0.1.0
